# Homeworld Remastered display setup — run by propnix-launcher (the `setupScript` tuning field) in the OUTER
# phase, BEFORE wine. It writes ONE file: the engine's own `commandLine.txt` options file, carrying the
# display resolution the compositor reports. The `wine.mounts` row in wine-tuning.nix binds this file into the
# game dir at the exact path the engine opens; NOTHING here knows where that is (see there for the coupling).
# Failure aborts the launch (the mkSetupScript wrapper supplies `set -euo pipefail`).
#
# WHY A FILE AND NOT `exeArgs`. The switches below are plain command-line options, so `exeArgs` would be the
# obvious home for them — but `exeArgs` is BAKED AT BUILD TIME and passed to the child verbatim (the launcher
# does no `$VAR` expansion, see cities-skylines), and the value we need is the LIVE display size. The HW2/HWRM
# engine's own answer to that is an options FILE: before it parses argv it seeds its option map with
# `params = ../commandLine.txt` and immediately loads that file, one option per line, with the same parser
# argv gets (disassembly cited in wine-tuning.nix). So the file is not a workaround — it is the engine's
# supported way to supply command-line options that are not on the command line.
#
# THE OPTIONS. All three are read by HomeworldRM.exe's video-settings resolver (VA 0x415032), which reads
# `screenResolutionW`/`screenResolutionH`/`screenFullscreen` from the player profile FIRST and then lets the
# command line overwrite them — so this is applied EVERY launch and self-corrects across a resolution or
# monitor change (the same discipline as Skyrim's iSize), and it works on a fresh prefix where no profile
# exists yet. Their spellings and semantics are from the exe's own code, not from lore:
#
#   w / h        `cmdline_get_int("w", &v)` / `("h", &v)` at 0x4150f3 / 0x41511e. Clamped to a FLOOR of
#                1024x768 unless `-forceResolution` is also given. We deliberately do NOT pass
#                `forceResolution`: the clamp only bites below 1024x768, and on a display that small the
#                engine's own minimum is the safer answer than a window it may not be able to render.
#   fullscreen   `cmdline_has("fullscreen")` at 0x4150ca → forces fullscreen on (`windowed` is the opposite
#                switch, at 0x4150dd). The profile default is already 1, but a profile that has been set
#                windowed would otherwise give a correctly-sized WINDOW rather than fullscreen; asserting it
#                every launch is the same call don't-starve's setup.sh makes for Klei's `fullscreen`.
#
# FILE FORMAT (parser at 0x7a9822): one option per line; a leading `-`/`+` is optional and stripped; `#` in
# the first column is a comment; names are matched case-insensitively; a line is `name = value`, `name value`
# or a bare flag. LF is fine — the reader is `fscanf(" %511[^\n]")`.
#
# Env provided by the launcher:
#   PROPNIX_WIDTH, PROPNIX_HEIGHT — the compositor's primary-output mode, physical px (may be UNSET if the
#                                   launcher could not read the display)
#   PROPNIX_STATE                 — the app state dir; the mount row's source lives here

out="$PROPNIX_STATE/commandLine.txt"
mkdir -p "$(dirname "$out")"

# No display facts → leave the file alone (better a stale resolution, or the empty file the mount row's
# `createIfNotExist` touched, than a half-written one that pins the game to nothing). Same call skyrim-se's
# setup.sh makes for iSize.
if [ -n "${PROPNIX_WIDTH:-}" ] && [ -n "${PROPNIX_HEIGHT:-}" ]; then
  {
    printf '# Generated by propnix on every launch from the compositor'"'"'s primary output. Edits are lost.\n'
    printf 'fullscreen\n'
    printf 'w = %s\n' "$PROPNIX_WIDTH"
    printf 'h = %s\n' "$PROPNIX_HEIGHT"
  } >"$out"
fi
